---
- hosts: virtualmachines
  become: true
  vars:
    install_apt:
      - git
      - net-tools
      - sysstat
      - fio
      - mdadm
      - cryptsetup
      - dnsmasq
    remove_apt: []
    install_snap: []
    remove_snap: []
  roles:
    - install
    - uninstall
    - rclocal
    - das16_v4_mount
    - dnsmasq
    - cron
    - sysctl