---
- name: "install packages for nfs container"
  apt:
    name:
      - nfs-kernel-server
    state: latest

- name: "export the data directory"
  lineinfile:
    path: /etc/exports
    insertafter: EOF
    line: /data {{ item }}(ro)
  loop: "{{ nfsallow }}"

- name: "start the nfs server"
  systemd:
    name: nfs-server
    state: started
    daemon_reload: yes
    enabled: yes

- name: "re-export the shares"
  command: exportfs -rav