---
- name: Remove default ephemeral mountpoint of /mnt
  mount:
    path: /mnt
    state: absent

- name: Mount temporary SATA as /sata instead
  mount:
    path: /containers
    src: /dev/disk/cloud/azure_resource-part1
    fstype: auto
    opts: defaults,nofail,x-systemd.requires=cloud-init.service,_netdev,comment=cloudconfig
    state: mounted

- name: Check if raid volume exists
  shell: mdadm /dev/md0 >/dev/null && echo no || echo yes
  register: result
  changed_when: false

- name: Set raid variable
  set_fact:
    raid: "{{ result.stdout }}"

- name: Create mdadm raid device from nvme drives
  shell: yes | mdadm --create --verbose /dev/md0 --level=0 --raid-devices=4 /dev/nvme0n1 /dev/nvme1n1 /dev/nvme2n1 /dev/nvme3n1
  when: encrypted and raid

- name: Create partition on /dev/md0
  shell: parted /dev/md0 --script mklabel gpt mkpart xfspart xfs 0% 100%
  when: encrypted and raid
  ignore_errors: yes

- name: Format xfs on /dev/md0p1
  shell: mkfs.xfs /dev/md0p1
  when: encrypted and raid
  ignore_errors: yes

- name: Add mountpoint to /mnt/nvme
  mount:
    path: /data
    src: /dev/md0p1
    fstype: xfs
    opts: noatime
    state: mounted
  when: encrypted and raid

- name: Check if encryption exists
  shell: cryptsetup status /dev/md0 >/dev/null && echo yes || echo no
  register: result
  changed_when: false

- name: Set encryption variable
  set_fact:
    encrypted: "{{ result.stdout }}"

- name: Encrypt the raid volume
  shell: cryptsetup /dev/md0 en0
  when: encrypted and raid

- name: Create partition /dev/mapper/en0
  shell: parted /dev/mapper/en0 --script mklabel gpt mkpart xfspart xfs 0% 100%
  when: encrypted and raid

- name: Format xfs on /dev/mapper/en0
  shell: mkfs.xfs /dev/mapper/en0p1
  when: encrypted and raid

- name: Add mountpoint to /mnt/nvme
  mount:
    path: /data
    src: /dev/mapper/en0p1
    fstype: xfs
    opts: noatime
    state: mounted
  when: encrypted and raid

