---
- name: Create directory for blob temp files
  file:
    path: /mnt/resource/blobfuse2tmp
    owner: root
    group: root
    state: directory
    mode: '777'

- name: Create mount directory
  file:
    path: /data
    owner: root
    group: root
    state: directory
    mode: '777'

- name: Get MS Package repo
  get_url:
    url: https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb
    dest: ./packages-microsoft-prod.deb

- name: Install MS Package repo
  command: dpkg -i packages-microsoft-prod.deb
  ignore_errors: yes

- name: Run "apt-get update"
  apt:
    update_cache: yes

- name: Install Fuse3
  apt:
    name: fuse3
    state: latest

- name: Install BlobFuse2
  apt:
    name: blobfuse2
    state: latest

- name: Copy mount file
  copy:
    src: files/mount.sh
    dest: /etc/blobfuse2/mount.sh
    owner: root
    group: root
    mode: '744'

- name: Mount storage through fstab
  mount:
    src: /etc/blobfuse2/mount.sh
    path: /data
    fstype: fuse
    opts: defaults,_netdev
    state: mounted
