---
- name: Create a directory on the temp disk for container data
  file:
    path: /mnt/containers
    state: directory
    mode: '0755'

- name: Create directory for blob temp files
  file:
    path: /mnt/resource/blobfuse2tmp
    owner: root
    group: root
    state: directory
    mode: '777'

- name: Create mount directory
  file:
    path: /data
    owner: root
    group: root
    state: directory
    mode: '777'

- name: Get MS Package repo
  get_url:
    url: https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb
    dest: ./packages-microsoft-prod.deb

- name: Install MS Package repo
  command: dpkg -i packages-microsoft-prod.deb
  ignore_errors: yes

- name: Run "apt-get update"
  apt:
    update_cache: yes

- name: Install Fuse3
  apt:
    name: fuse3
    state: latest

- name: Install BlobFuse2
  apt:
    name: blobfuse2
    state: latest

- name: Mount storage account
  command: blobfuse2 mount /data --config-file=/etc/blobfuse2/config.yaml
  ignore_errors: yes

- name: Add mount point to fstab
  mount:
    path: /data
    src: blobfuse2
    fstype: fuse
    opts: defaults,_netdev,--config-file=/etc/blobfuse2/config.yaml
    state: present
