---
- name: Create a directory on the temp disk for container data
  file:
    path: /mnt/containers
    state: directory
    mode: '0755'

- name: Create directory for blob temp files
  file:
    path: /mnt/resource/blobfuse2tmp
    owner: root
    group: root
    state: directory
    mode: '777'

- name: Create mount directory
  file:
    path: /data
    owner: root
    group: root
    state: directory
    mode: '777'

- name: Create config directory
  file:
    path: /etc/blobfuse2
    owner: root
    group: root
    state: directory
    mode: '755'

- name: Copy config file
  copy:
    src: files/config.yaml
    dest: /etc/blobfuse2/config.yaml
    owner: root
    group: root
    mode: '644'

- name: Update config with storage name
  replace:
    path: /etc/blobfuse2/config.yaml
    regexp: '_ACCT_'
    replace: '{{storage_name}}'

- name: Get MS Package repo
  command: wget https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb

- name: Install MS Package repo
  command: dpkg -i packages-microsoft-prod.deb
  ignore_errors: yes

- name: Run "apt-get update"
  apt:
    update_cache: yes

- name: Install Fuse3
  apt:
    name: fuse3
    state: latest

- name: Install BlobFuse2
  apt:
    name: blobfuse2
    state: latest

- name: Mount storage account
  mount:
    path: /data
    fstype: fuse
    opts: defaults,_netdev,--config-file=/etc/blobfuse2/config.yaml
    state: mounted
